cameras:
  - po: 1
    url: video/video_tear.mp4
  - po: 2
    url: video/video_tear.mp4
  - po: 3
    url: video/video_tear.mp4
    
api: 
  url: http://localhost:5000
  cliente: 1000
  login: admin
  senha: P@ssw0rd
  timeout: 10

train_duration_sec: 60